[mongodb]
mongodb.kakuturu.online

[catalogue]
catalogue.kakuturu.online

[redis]
redis.kakuturu.online

[user]
user.kakuturu.online

[cart]
cart.kakuturu.online

[frontend]
frontend.kakuturu.online

[mysql]
mysql.kakuturu.online

[shipping]
shipping.kakuturu.online

[rabbitmq]
rabbitmq.kakuturu.online

[payment]
payment.kakuturu.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

