- name: app setup
  include_role:
    name: app-setup
    tasks_from: common

- name: python3 installation
  include_role:
    name: python
    tasks_from: common

- name: systemd setup
  include_role:
    name: systemd
    tasks_from: common

